spring:
  application:
    name: pelicula-service
  graphql:
    path: /graphql
    graphiql:
      enabled: true
  data:
    mongodb:
      auto-index-creation: true
      username: root
      password: root
      uri: mongodb://localhost:27017/cinemaflow

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: dev
debug: true
server:
  port: 0   #8090
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/